---
- name: Shutdown
  hosts: all
  become: yes
  remote_user: root
  tasks:
  - name: Shutdown VM without waiting for SSH timeout
    ansible.builtin.shell: sleep 2 && shutdown -h now
    async: 1
    poll: 0
    become: true
    ignore_errors: true