---
- name: Create a user with sudo privileges
  hosts: all
  become: yes
  remote_user: root
  tasks:
    - name: Unconditionally shut down the machine with all defaults
      command: /sbin/shutdown -h now
